Implement template library
SQE22-RoboticWelding/model-transformer-welding-backend pull request #54
Opened 2022-07-04 18:29 UTC by janosbrodbeck

**Based on #49 and #50**
This PR is implements my current **idea** how to implement pre-defined templates in the backend. Seeding templates into the database is not quite so trivial (when to update? What, if the template has been deleted? Seed it again? Etc.), so I came up with a simpler solution, which should fit our current needs. But is a bit more work for the frontend I guess.

* Adds an endpoint, which returns a list of pre-defined templates from the backend. They are not assignable to robot types, but instead can be "browsed" (frontend part) when the user wants to create a new template. The user could then look what templates are in the library and could use it as a starting point for their template. The List of templates is basically a normal Template structure wise. We can have a call about this idea as well to talk about some details and whether it is feasible.
Nonetheless: This results in way less problems when templates change, are deleted or added → less headache for the backend.
* A template file `.template` consists of a JSON in the first line with metadata, the rest of the file is the template itself
* Added a test, which tests if all templates can be loaded

2022-07-05 17:40 UTC, dolevi-tub requested changes

2022-07-05 17:40 UTC, dolevi-tub commented on src/app/templates/getter.py
> +def __get_templates_in_path():
```suggestion
def __get_templates_in_path() -> List[bytes]:
```

2022-07-05 17:40 UTC, dolevi-tub commented on src/app/templates/getter.py
> +        f = open(template, "r")
```suggestion
        with open(template, "r") as file:
        # ...
```

2022-07-05 19:59 UTC, janosbrodbeck commented on src/app/templates/getter.py
> +        f = open(template, "r")
Addressed

2022-07-05 19:59 UTC, janosbrodbeck commented on src/app/templates/getter.py
> +__path_to_testdata = Path(__file__).parent
Addressed, good old copypasta

2022-07-05 19:59 UTC, janosbrodbeck commented on src/app/templates/getter.py
> +def __get_templates_in_path():
Addressed

2022-07-05 19:59 UTC, janosbrodbeck commented on src/app/templates/getter.py
> +        if os.path.isfile(filepath) and path.split(".")[-1] == "template":
Addressed

2022-07-05 20:00 UTC, janosbrodbeck commented on src/app/templates/getter.py
> +        f = open(template, "r")
Addressed

2022-07-05 20:00 UTC, janosbrodbeck commented on src/app/templates/getter.py
> +            print(f"Template file '{os.path.basename(template)}' cannot be loaded: {e}")
Added the comment, thanks :)

2022-07-05 20:05 UTC, janosbrodbeck commented on src/app/templates/getter.py
> +        if os.path.isfile(filepath) and path.split(".")[-1] == "template":
Placed now a `# noqa` here ¯\_(ツ)_/¯

2022-07-06 18:38 UTC, janosbrodbeck commented
I am thinking about adding a `version` field as well

2022-07-06 22:56 UTC, janosbrodbeck commented
Added support for blockly templates and added a very basic example blockly template. Sorry for including a massive library like `beautifulsoup` but the built-in XML parser from python outputs crappy ""prettified"" code.  It's not completely how I want it right now, but it's good enough if someone has a quick look at it.

2022-07-06 23:30 UTC, janosbrodbeck commented
Implemented support for blockly templates. Blockly templates arerettified again, as the resulted generated code is not well formatted. Also added an example blockly template for the niryo one (new stack).

2022-07-07 07:47 UTC, dolevi-tub approved these changes
Nothing to note :+1:

2022-07-07 11:18 UTC, merged